language: csharp
mono: none
dotnet: 3.1.101
dist: bionic
script:
  - cd ./SMAL
  - dotnet build -c Debug
  - dotnet build -c Release
  - cd ../Tests
  - dotnet build -c Release
  - dotnet test
